"""LangChain `StructuredTool` wrappers around `AuthoringToolRegistry`.

Each registry method is exposed as a `StructuredTool` with a Pydantic args-schema
autogenerated from the existing JSON schemas in `tool_definitions()`.  The
wrapper performs no logic — it forwards kwargs to the registry method and
returns the registry's result dict unchanged.

Keeping the JSON schemas in `tools.py` as the single source of truth means the
two callers (the LangChain path and any direct `dispatch()` callers) cannot
drift out of sync.
"""

from __future__ import annotations

from typing import Any, Callable

from pydantic import BaseModel, ConfigDict, create_model

from .tools import AuthoringToolRegistry, tool_definitions


# ── JSON-schema → Pydantic type mapping ───────────────────────────────

_JSON_PRIMITIVE: dict[str, type] = {
    "string": str,
    "number": float,
    "integer": int,
    "boolean": bool,
}


def _python_type_for(json_schema: dict[str, Any]) -> Any:
    """Return a Python type annotation matching a JSON-schema property."""
    json_type = json_schema.get("type")
    if json_type in _JSON_PRIMITIVE:
        return _JSON_PRIMITIVE[json_type]
    if json_type == "array":
        items = json_schema.get("items") or {}
        item_type = items.get("type")
        if item_type == "object":
            # Nested objects become free-form dicts so the model can supply any
            # compatible shape; the registry method validates contents.
            return list[dict[str, Any]]
        if item_type in _JSON_PRIMITIVE:
            return list[_JSON_PRIMITIVE[item_type]]
        return list[Any]
    if json_type == "object":
        return dict[str, Any]
    return Any


def _args_model_for_tool(tool_def: dict[str, Any]) -> type[BaseModel]:
    """Build a Pydantic model representing one tool's argument shape."""
    function = tool_def["function"]
    name = function["name"]
    parameters = function.get("parameters") or {}
    properties: dict[str, dict[str, Any]] = parameters.get("properties") or {}
    required: set[str] = set(parameters.get("required") or [])

    fields: dict[str, Any] = {}
    for prop_name, prop_schema in properties.items():
        py_type = _python_type_for(prop_schema)
        description = prop_schema.get("description")
        if prop_name in required:
            fields[prop_name] = (py_type, ...) if description is None else (
                py_type,
                _field_with_description(description, default=...),
            )
        else:
            optional_type = py_type | None  # Python 3.10+ syntax
            fields[prop_name] = (
                optional_type,
                _field_with_description(description, default=None),
            )

    model_name = "".join(part.capitalize() for part in name.split("_")) + "Args"
    return create_model(
        model_name,
        __config__=ConfigDict(arbitrary_types_allowed=True, extra="ignore"),
        **fields,
    )


def _field_with_description(description: str | None, *, default: Any):
    from pydantic import Field
    if description is None:
        return Field(default=default)
    return Field(default=default, description=description)


# ── Public API ────────────────────────────────────────────────────────

def make_lc_tools(
    registry: AuthoringToolRegistry,
    *,
    allowed: "set[str] | tuple[str, ...] | None" = None,
    denied: "set[str] | tuple[str, ...] | None" = None,
) -> list[Any]:
    """Wrap registry methods as `StructuredTool`s.

    Args:
        registry: the AuthoringToolRegistry whose dispatch table backs the
            wrapped tools.
        allowed: when set, only tools with a matching name are returned.
            Used by category-agent prefetch to give each subagent a focused
            toolset (e.g. only `search_labware` + `get_labware`).
        denied: when set, tools with a matching name are withheld. Used by
            the narrowed-scope `enforce` mode to remove catalog search.
    """
    from langchain_core.tools import StructuredTool

    allowed_set = set(allowed) if allowed is not None else None
    denied_set = set(denied) if denied is not None else None
    tools: list[Any] = []
    fn_map = registry.functions()
    for tool_def in tool_definitions():
        name = tool_def["function"]["name"]
        if allowed_set is not None and name not in allowed_set:
            continue
        if denied_set is not None and name in denied_set:
            continue
        description = tool_def["function"]["description"]
        registry_fn = fn_map.get(name)
        if registry_fn is None:
            raise RuntimeError(
                f"tool_definitions() lists {name!r} but AuthoringToolRegistry.functions() does not"
            )
        args_model = _args_model_for_tool(tool_def)
        tools.append(
            StructuredTool.from_function(
                func=_make_dispatcher(registry, name),
                name=name,
                description=description,
                args_schema=args_model,
            )
        )
    return tools


def _make_dispatcher(registry: AuthoringToolRegistry, name: str) -> Callable[..., dict[str, Any]]:
    """Return a closure that routes through `registry.dispatch` for logging parity.

    Going through `dispatch()` rather than calling the method directly keeps the
    `registry.calls` log identical to the legacy code path, which existing tests
    (`test_authoring_session.py::test_session_repair_lock_*`) rely on.
    """
    def _call(**kwargs: Any) -> dict[str, Any]:
        return registry.dispatch(name, kwargs)
    _call.__name__ = f"dispatch_{name}"
    return _call
